package:
  name: bayeslite
  version: {{ CONDA_PACKAGE_VERSION }}

source:
  path: ../

build:
  script: python setup.py install

requirements:
  build:
    - cython 0.23.*
    - git
    - jsonschema
    - numpy 1.11.*
    - python 2.7.*
  run:
    - apsw
    - cgpm
    - crosscat
    - jsonschema
    - loom 0.2.10
    - numpy 1.11.*
    - scipy 0.17.*
    - six 1.10.*

test:
  requires:
    - apsw
    - cgpm 2018.02.15*
    - crosscat 2017.12.05*
    - loom 0.2.10
    - pandas 0.18.*
    - pytest 2.8.*
    - python 2.7.*
  commands:
    - python -m pytest --pyargs bayeslite

about:
  home: https://github.com/probcomp/bayeslite
  license: Apache
  license_file: LICENSE.txt
